### PR TITLE
Optimized the code

### PR DESCRIPTION
**Pull request by Hiiirad**
Here are some ways to optimize the code:

- **Use built-in functions instead of custom functions.** The `urlparse()` and `BeautifulSoup()` functions are both built-in functions in Python, so you can use them instead of writing your own custom functions. This will make your code more concise and easier to read.
- **Use list comprehensions instead of for loops.** List comprehensions are a powerful feature of Python that can be used to create lists more efficiently than for loops. In this case, you can use a list comprehension to create a list of all the external domains in the HTML document.

### CODE REVIEW

**Comment by Hiiirad** [comment]
Also, here's the result for the comparison of the optimized code with the old code:

```bash
$ time python get_external_domains.py 
['maps.google.com', 'news.google.com', 'accounts.google.com', 'mail.google.com', 'drive.google.com', 'www.youtube.com', 'play.google.com']

real    0m8.176s
user    0m0.138s
sys     0m0.025s
```

```bash
$ time python get_external_domains_optimized.py 
['accounts.google.com', 'news.google.com', 'www.youtube.com', 'drive.google.com', 'mail.google.com', 'maps.google.com', 'play.google.com']

real    0m1.279s
user    0m0.161s
sys     0m0.021s
```

**Comment by hiddify-com** [comment]
Great thanks
However it seems that you ignored src tags am i right?
```
external_domains = [link.get('href',link.get('src')) for link in links]
external_domains = [urlparse(link).netloc for link in external_domains if link not is None and (link.startswith('http') or link.startswith('//'))]
external_domains =[d for d in external_domains if d != domain]
```
what do you think about this modification?

**Comment by Hiiirad** [comment]
It looks great. Your modified code and mine works the same except for the `src` tag that I removed. You'll be fine with both versions :smile:

**Comment by hiddify-com** [comment]
would you please add src to your code and add pull request? thank you

**Comment by Hiiirad** [comment]
I just added the `src` tag. I believe it's ready.

**Comment by Hiiirad** [comment]
I updated my PR based on your request on this PR. There's no need for another PR. Thanks

**Comment by hiddify-com** [comment]
داداش متوجه نشدم چی گفتی

**Comment by Hiiirad** [comment]
میگم شما به من گفتی که تگ src هم به کد اضافه کنم و PR بزنم، منم کد رو اصلاح کردم و روی PR اولیه خودم اصلاحش کردم. اگر کد مورد تایید هست، می‌تونی همین PR فعلی رو قبول کنی.

**Comment by hiddify-com** [comment]
خوب دو تا اشکال داشت مشخص کردم دیگه
بببین دوجا چک نمیکنیش

**Pull request closed without merging**
